import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        display: ["Plus Jakarta Sans", "sans-serif"],
      },
      colors: {
        // Viport Design System Colors
        "primary": "#001b31",
        "on-primary": "#ffffff",
        "primary-container": "#09304e",
        "on-primary-container": "#7898bc",
        "primary-fixed": "#cfe4ff",
        "primary-fixed-dim": "#a9caef",
        "on-primary-fixed": "#001d34",
        "on-primary-fixed-variant": "#284968",
        "secondary": "#855300",
        "on-secondary": "#ffffff",
        "secondary-container": "#ffa92b",
        "on-secondary-container": "#6b4200",
        "secondary-fixed": "#ffddb8",
        "secondary-fixed-dim": "#ffb95f",
        "on-secondary-fixed": "#2a1700",
        "on-secondary-fixed-variant": "#653e00",
        "tertiary": "#001f01",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#003702",
        "on-tertiary-container": "#29ac28",
        "tertiary-fixed": "#7ffe6f",
        "tertiary-fixed-dim": "#62e056",
        "on-tertiary-fixed": "#002201",
        "on-tertiary-fixed-variant": "#005305",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface": "#f8f9ff",
        "on-surface": "#001d34",
        "surface-variant": "#cfe4ff",
        "on-surface-variant": "#43474d",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eef4ff",
        "surface-container": "#e4efff",
        "surface-container-high": "#daeaff",
        "surface-container-highest": "#cfe4ff",
        "surface-dim": "#c0ddff",
        "surface-bright": "#f8f9ff",
        "surface-tint": "#416181",
        "inverse-surface": "#0d3251",
        "inverse-on-surface": "#e9f1ff",
        "inverse-primary": "#a9caef",
        "outline": "#73777e",
        "outline-variant": "#c3c7ce",
        "background": "#f8f9ff",
        "on-background": "#001d34",
        // Shadcn ui compatible tokens (kept for components)
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-up": {
          from: { opacity: "0", transform: "translateY(30px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-up": "fade-up 0.8s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
